version: "3.7"
services:
  app:
    build:
      args:
        user: vinicius
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: manager-controll-go
    container_name: manager-controll-go-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - manager-controll-go

  db:
    image: mysql:5.7
    container_name: manager-controll-go-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - manager-controll-go

  nginx:
    image: nginx:latest
    container_name: manager-controll-go-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - manager-controll-go



networks:
  manager-controll-go:
    driver: bridge
